# Generated by Django 3.2 on 2025-09-26 11:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('approval_status', models.CharField(default='pending', max_length=15)),
                ('LOGIN', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CrowdFundingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('amount_needed', models.IntegerField()),
                ('current_amount', models.IntegerField()),
                ('status', models.CharField(default='pending', max_length=10)),
                ('Date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HelpRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='NormalUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.CharField(max_length=100)),
                ('address', models.TextField(blank=True, null=True)),
                ('LOGIN', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('requirements', models.TextField()),
                ('status', models.CharField(default='open', max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.companyprofile')),
            ],
        ),
        migrations.CreateModel(
            name='SkillCenterProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=15)),
                ('approval_status', models.CharField(default='pending', max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='')),
                ('LOGIN', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(upload_to='')),
                ('NormalUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.normaluser')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='videos/')),
                ('title', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.program')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField()),
                ('review', models.TextField()),
                ('date', models.DateField()),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.program')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.normaluser')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_meet_link', models.URLField()),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.program')),
            ],
        ),
        migrations.AddField(
            model_name='program',
            name='skill_center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.skillcenterprofile'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('read_status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('NormalUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.normaluser')),
                ('Vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.vacancy')),
            ],
        ),
        migrations.CreateModel(
            name='HelpResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('willingness_message', models.TextField()),
                ('responded_at', models.DateTimeField(auto_now_add=True)),
                ('help_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.helprequest')),
                ('responder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.normaluser')),
            ],
        ),
        migrations.AddField(
            model_name='helprequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.normaluser'),
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('donated_at', models.DateTimeField(auto_now_add=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.normaluser')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.crowdfundingrequest')),
            ],
        ),
        migrations.AddField(
            model_name='crowdfundingrequest',
            name='NormalUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.normaluser'),
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_text', models.TextField()),
                ('reply_text', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('NormalUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.normaluser')),
            ],
        ),
        migrations.CreateModel(
            name='AppReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField()),
                ('review', models.TextField()),
                ('Date', models.DateField(auto_now_add=True)),
                ('NormalUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.normaluser')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='applied', max_length=10)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('NormalUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.normaluser')),
                ('Resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.resume')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.vacancy')),
            ],
        ),
    ]
